// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/roles": {
    params: {};
  };
  "/permissions": {
    params: {};
  };
  "/companies": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/inventory": {
    params: {};
  };
  "/customers": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/about" | "/users" | "/roles" | "/permissions" | "/companies" | "/products" | "/inventory" | "/customers";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/users.tsx": {
    id: "routes/users";
    page: "/users";
  };
  "routes/roles.tsx": {
    id: "routes/roles";
    page: "/roles";
  };
  "routes/permissions.tsx": {
    id: "routes/permissions";
    page: "/permissions";
  };
  "routes/companies.tsx": {
    id: "routes/companies";
    page: "/companies";
  };
  "routes/products.tsx": {
    id: "routes/products";
    page: "/products";
  };
  "routes/inventory.tsx": {
    id: "routes/inventory";
    page: "/inventory";
  };
  "routes/customers.tsx": {
    id: "routes/customers";
    page: "/customers";
  };
};